server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jalmeida08/data-repo
        #native:
         # search-locations: 
          #- /home/stefanini/Documentos/pessoal/desenvolvimento/data-repo/
