server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: 
          - /home/stefanini/Documentos/pessoal/desenvolvimento/data-repo/